Added in width to be inserted from meta
chaseconey/nova-external-image pull request #2
Opened 2018-11-10 02:52 UTC by claytonnarcis

This allows custom size rather than depending on actual image size

2019-04-03 16:19 UTC, mrvnklm commented
@chaseconey Could you merge? Cheers

2019-08-13 03:15 UTC, chaseconey commented on composer.json
> +  "name": "claytonnarcis/nova-external-image-with-width",
I can merge this up, but you will have to undo these changes

2019-08-13 03:15 UTC, chaseconey requested changes
Just need to revert the `composer.json` and we should be good to go.

2019-08-13 03:17 UTC, chaseconey commented
Closing in favor of #4

2019-08-13 03:17 UTC, closed without merging